"""AST to Python transpiler for Mandate."""

from __future__ import annotations

from typing import Any

from .ast_nodes import (
    ArrayType,
    Assignment,
    BinaryOp,
    EnumType,
    FieldAccess,
    FunctionCall,
    Identifier,
    IfStmt,
    Literal,
    MandateBlock,
    OptionalType,
    PrimitiveType,
    Program,
    RangeExpr,
    RecordType,
    ReturnStmt,
    SynthesizeExpr,
    UnaryOp,
    UnionType,
    VerifyExpr,
)


class Transpiler:
    """Convert Mandate AST to Python source code."""

    def __init__(self):
        self.indent = 0
        self.lines: list[str] = []
        self.needs_synthesize = False
        self.needs_verify = False

    def emit(self, text: str = "") -> None:
        """Emit a line of Python code."""
        if text:
            self.lines.append("    " * self.indent + text)
        else:
            self.lines.append("")

    def transpile_program(self, program: Program) -> str:
        """Transpile a full program to Python."""
        for mandate in program.mandates:
            self.transpile_mandate(mandate)

        # Build header
        header_lines = [
            '"""Generated by the Mandate transpiler."""',
            "",
        ]
        if self.needs_synthesize:
            header_lines.append(
                "from mandate.synthesize import synthesize_call"
            )
        if self.needs_verify:
            header_lines.append(
                "from mandate.verify import run_verify, VerifyResult"
            )
        if self.needs_synthesize or self.needs_verify:
            header_lines.append("")

        return "\n".join(header_lines + self.lines) + "\n"

    def transpile_mandate(self, m: MandateBlock) -> str:
        """Transpile a single mandate block."""
        # Function signature
        self.emit(f"def {m.name}(input_data: dict) -> dict:")
        self.indent += 1

        # Docstring
        if m.intent:
            self.emit(f'"""{m.intent}"""')

        # Requires declarations as comments
        for req in m.requires:
            params_str = ", ".join(f"{k}: {v}" for k, v in req.params.items())
            self.emit(f"# requires: {req.name}({params_str}) -> {req.return_type}")

        self.emit()

        # Flow
        if m.flow:
            self.emit("# Flow")
            for stmt in m.flow:
                self.emit_statement(stmt)
            self.emit()

        # Verify
        if m.verify:
            self.needs_verify = True
            self.emit("# Verify")
            self.emit("_verify_results = [")
            self.indent += 1
            for vexpr in m.verify:
                expr_py = self.expr_to_python(vexpr.expression, output_var="output")
                source = vexpr.source.replace('"', '\\"')
                self.emit(f'("{source}", {expr_py}),')
            self.indent -= 1
            self.emit("]")
            self.emit("for _desc, _passed in _verify_results:")
            self.indent += 1
            self.emit("if not _passed:")
            self.indent += 1
            self.emit('raise AssertionError(f"Verify failed: {_desc}")')
            self.indent -= 2
            self.emit()

        # Handoff as comments
        if m.handoff:
            self.emit("# Handoff")
            self.emit(f"# worked: {m.handoff.worked}")
            self.emit(f"# failed: {m.handoff.failed}")
            self.emit(f"# next: {m.handoff.next_recommendation}")
            self.emit()

        # If no explicit return in flow, return empty dict
        if not any(isinstance(s, ReturnStmt) for s in m.flow):
            self.emit("return {}")

        self.indent -= 1
        self.emit()

        return "\n".join(self.lines)

    def emit_statement(self, stmt: Any) -> None:
        """Emit a flow statement."""
        if isinstance(stmt, Assignment):
            rhs = self.expr_to_python(stmt.expression)
            self.emit(f"{stmt.target} = {rhs}")

        elif isinstance(stmt, ReturnStmt):
            fields = ", ".join(
                f'"{k}": {self.expr_to_python(v)}'
                for k, v in stmt.fields.items()
            )
            self.emit(f"output = {{{fields}}}")
            self.emit("return output")

        elif isinstance(stmt, IfStmt):
            cond = self.expr_to_python(stmt.condition)
            self.emit(f"if {cond}:")
            self.indent += 1
            for s in stmt.body:
                self.emit_statement(s)
            self.indent -= 1
            if stmt.else_body:
                self.emit("else:")
                self.indent += 1
                for s in stmt.else_body:
                    self.emit_statement(s)
                self.indent -= 1

    def expr_to_python(self, expr: Any, output_var: str = "output") -> str:
        """Convert an expression AST node to Python source."""
        if isinstance(expr, Literal):
            if expr.type == "string":
                return repr(expr.value)
            if expr.type == "bool":
                return "True" if expr.value else "False"
            return str(expr.value)

        if isinstance(expr, Identifier):
            if expr.name == "input":
                return "input_data"
            if expr.name == "output":
                return output_var
            return expr.name

        if isinstance(expr, FieldAccess):
            obj = self.expr_to_python(expr.object, output_var)
            if expr.field == "length":
                return f"len({obj})"
            # For dict-like access (input, output, records)
            if isinstance(expr.object, Identifier) and expr.object.name in ("input", "output"):
                return f'{obj}["{expr.field}"]'
            # Nested field access on a dict
            return f'{obj}["{expr.field}"]'

        if isinstance(expr, FunctionCall):
            args = ", ".join(self.expr_to_python(a, output_var) for a in expr.args)
            # Map builtins
            builtin_map = {"sort": "sorted", "len": "len", "str": "str", "int": "int", "float": "float"}
            name = builtin_map.get(expr.name, expr.name)
            return f"{name}({args})"

        if isinstance(expr, SynthesizeExpr):
            self.needs_synthesize = True
            given_parts = []
            for g in expr.given:
                py = self.expr_to_python(g, output_var)
                # Try to extract a name for the key
                key = self._expr_key_name(g)
                given_parts.append(f'"{key}": {py}')
            given_dict = "{" + ", ".join(given_parts) + "}"
            type_str = self._type_to_string(expr.produce_type)
            instr = expr.instruction.replace('"', '\\"')
            return (
                f'synthesize_call(\n'
                f'{"    " * (self.indent + 1)}given={given_dict},\n'
                f'{"    " * (self.indent + 1)}produce_type="{type_str}",\n'
                f'{"    " * (self.indent + 1)}instruction="{instr}",\n'
                f'{"    " * self.indent})'
            )

        if isinstance(expr, BinaryOp):
            left = self.expr_to_python(expr.left, output_var)

            if expr.op == "in" and isinstance(expr.right, RangeExpr):
                low = self.expr_to_python(expr.right.low, output_var)
                high = self.expr_to_python(expr.right.high, output_var)
                return f"{low} <= {left} <= {high}"

            right = self.expr_to_python(expr.right, output_var)

            op_map = {
                "==": "==", "!=": "!=", ">": ">", "<": "<",
                ">=": ">=", "<=": "<=", "+": "+", "-": "-",
                "*": "*", "/": "/", "and": "and", "or": "or",
                "contains": None, "is": None, "in": "in",
            }
            if expr.op == "contains":
                return f"{right} in {left}"
            if expr.op == "is":
                return f"isinstance({left}, {right})"

            py_op = op_map.get(expr.op, expr.op)
            return f"({left} {py_op} {right})"

        if isinstance(expr, UnaryOp):
            operand = self.expr_to_python(expr.operand, output_var)
            if expr.op == "not":
                return f"not {operand}"
            return f"-{operand}"

        return repr(expr)

    def _expr_key_name(self, expr: Any) -> str:
        """Extract a key name from an expression for dict building."""
        if isinstance(expr, Identifier):
            return expr.name
        if isinstance(expr, FieldAccess):
            return expr.field
        return "value"

    def _type_to_string(self, t: Any) -> str:
        if isinstance(t, PrimitiveType):
            return t.name
        if isinstance(t, ArrayType):
            return f"{self._type_to_string(t.element_type)}[]"
        if isinstance(t, RecordType):
            return "record"
        if isinstance(t, EnumType):
            return t.name
        if isinstance(t, UnionType):
            return " | ".join(self._type_to_string(sub) for sub in t.types)
        return str(t)


def transpile(program: Program) -> str:
    """Transpile a Mandate program AST to Python source."""
    t = Transpiler()
    return t.transpile_program(program)
